
export enum EnvVars {
    COMPANY_NAME = "COMPANY_NAME",
    SUPABASE_URL = "SUPABASE_URL",
    SUPABASE_SERVICE_ROLE_KEY = "SUPABASE_SERVICE_ROLE_KEY",
    RESEND_API_KEY = "RESEND_API_KEY",
    ENV = "ENV",
    RECARGUITAS_BASE_URL = "RECARGUITAS_BASE_URL",
    COURIER_KEY = "COURIER_KEY",
    FIREBASE_PRIVATE_KEY = "FIREBASE_PRIVATE_KEY",
    FIREBASE_KID = "FIREBASE_KID",
    FIREBASE_SERVICE_URL = "FIREBASE_SERVICE_URL",
    FIREBASE_FCM_URL = "FIREBASE_FCM_URL",
    STRIPE_API_KEY = "STRIPE_API_KEY",
    JWT_SECRET = "JWT_SECRET",
    ENTREGAS_CUBA_AGENCY_KEY = "ENTREGAS_CUBA_AGENCY_KEY",
    ENTREGAS_CUBA_URL = "ENTREGAS_CUBA_URL"
}
